[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc = "0.8.20"

[rpc_endpoints]
celo_sepiloa = "https://celo-sepolia.drpc.org"
celo_alfajores = "https://alfajores-forno.celo-testnet.org"
